name: cp_app
description: Flutter cp app

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.4.0

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  flutter_facebook_login: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/